package CombiningMultipleCompletableFutures;

import java.util.concurrent.CompletableFuture;

public class runAfterBothDemo {
    public static void main(String[] args) {

        CompletableFuture<Integer> Future1 = CompletableFuture.supplyAsync(() -> {
            System.out.println("The Value Generated By Future 1");
            return 100;
        });

        CompletableFuture<Integer> Future2 = CompletableFuture.supplyAsync(() -> {
            System.out.println("The Value is Generated By Future 2");
            return 20;
        });

        Future1.runAfterBoth(Future2, () -> {
            System.out.println("The Final is ");
        });
    }
}
